env:
  browser: true
  es2021: true
extends:
  - standard
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  curly: [error, multi-or-nest, consistent]
  generator-star-spacing:
    - error
    - before: false
      after: true
      anonymous: neither
      method: before
  multiline-ternary: off
  no-sequences: off
  no-sparse-arrays: off
  no-void: off
  no-extra-parens: off
  no-return-assign: off
  one-var: off
  prefer-const: off
  promise/param-names: off
  quote-props: [error, consistent-as-needed]
  semi: [error, always]
  space-before-function-paren:
    - error
    - anonymous: never
      asyncArrow: always
      named: never
  yield-star-spacing: [error, after]
