#! /usr/bin/env node

const { spawn, spawnSync } = require('child_process');
const { readFileSync } = require('fs');
const { join } = require('path');

function isUnpublished(pkg) {
  let published = spawnSync('npm', ['view', pkg.name, 'versions']);

  if (published.status === 0) {
    let versions = JSON.parse(published.stdout.toString().replace(/'/g, '"'));
    return !versions.includes(pkg.version);
  } else {
    return true;
  }
}

function publish(pkg, args) {
  if (isUnpublished(pkg)) {
    spawn('npm', ['publish', ...args], {
      stdio: [null, 1, 2]
    }).on('exit', process.exit);
  }
}

// get the current package and publish it with any passed arguments
const cwd = process.cwd();
const pkg = JSON.parse(readFileSync(join(cwd, 'package.json')));
const [,,...args] = process.argv;

publish(pkg, args);
