name: Pull Request
on:
  pull_request_target:
jobs:
  automerge:
    name: Automerge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Automerge and Approve
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GH_PAT }}
          script: |
            await github.graphql(`
              mutation($id: ID!) {
                enablePullRequestAutoMerge(input: {
                  mergeMethod: SQUASH,
                  pullRequestId: $id
                }) { clientMutationId }
                addPullRequestReview(input: {
                  event: APPROVE,
                  pullRequestId: $id
                }) { clientMutationId }
              }
            `, {
              id: context.payload
                .pull_request.node_id
            });
