name: Test
on: push
jobs:
  install:
    name: Install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: v1/${{ runner.os }}/node-18/${{ hashFiles('yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-18/
      - run: yarn

  lint:
    name: Lint
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: v1/${{ runner.os }}/node-18/${{ hashFiles('yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-18/
      - run: yarn
      - run: yarn lint

  build:
    name: Build
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: v1/${{ runner.os }}/node-18/${{ hashFiles('yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-18/
      - run: yarn
      - run: yarn build

  test:
    name: Test
    needs: [install]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - uses: actions/cache@v2
        with:
          path: node_modules
          key: v1/${{ runner.os }}/node-18/${{ hashFiles('yarn.lock') }}
          restore-keys: v1/${{ runner.os }}/node-18/
      - run: yarn
      - name: Run tests
        run: yarn test:coverage
      - uses: codecov/codecov-action@v1
        with:
          files: coverage/**/*.json
